name: learn-github-actions-name
run-name: ${{ github.actor }} is learning run-name2
on: [push]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python --version
      - run: cat Dockerfile

